# syntax=docker/dockerfile:1

FROM node:20-slim AS build
WORKDIR /app
COPY package*.json .
COPY patches/ ./patches/
RUN npm ci
COPY . .
RUN npm run build:job-worker
 
FROM public.ecr.aws/lambda/nodejs:20 AS runner
ENV NODE_ENV=production
COPY --from=build /app/dist/job-worker.js ${LAMBDA_TASK_ROOT}
CMD ["job-worker.handler"]

FROM public.ecr.aws/lambda/nodejs:20 AS dev
COPY --from=build /app/dist/job-worker.js ${LAMBDA_TASK_ROOT}
CMD ["job-worker.handler"]

