# syntax=docker/dockerfile:1

FROM node:22-slim AS build
WORKDIR /app
COPY package*.json .
COPY patches/ ./patches/
RUN npm ci
COPY . .
COPY src/assets/fonts dist/fonts/
RUN npm run build:job-worker-heavy

FROM node:22-slim AS runner
ENV NODE_ENV=production
ENV PDFKIT_DATA_DIR=/app/data
WORKDIR /app
COPY package*.json .
RUN ["npm", "install", "better-sqlite3"]
RUN ["rm", "package*.json"]
COPY --from=build /app/dist/ecs-worker.js ./dist/ecs-worker.js
COPY --from=build /app/node_modules/pdfkit/js/data ./data
COPY --from=build /app/dist/fonts ./fonts
CMD ["node", "dist/ecs-worker.js"]
