import { requestHandler } from "@tanstack/react-start/server";
import { runWithStartContext } from "@tanstack/start-storage-context";
// @ts-expect-error This is a virtual module generated by the compiler
import { getServerFnById } from "#tanstack-start-server-fn-resolver";

interface RunServerFnOptions {
  method?: "GET" | "POST";
  sessionId?: string;
  data?: unknown;
  headers?: Record<string, string>;
  context?: Record<string, unknown>;
  request?: Request;
}

interface ServerFnExecutionResult {
  result?: unknown;
  error?: unknown;
  context?: unknown;
}

export async function runServerFn<T = unknown>(
  serverFn: {
    method?: "GET" | "POST";
    serverFnMeta?: {
      id: string;
    };
  },
  options: RunServerFnOptions = {},
): Promise<{ result: T; response: Response; context: unknown }> {
  const serverFnId = serverFn.serverFnMeta?.id;
  if (!serverFnId) {
    throw new Error(
      "Expected a transformed server function reference with serverFnMeta.id",
    );
  }

  const compiledServerFn = await getServerFnById(serverFnId);
  const method = options.method ?? serverFn.method ?? "GET";

  const headers = { ...options.headers };
  if (options.sessionId) {
    headers["cookie"] = `session=${options.sessionId}`;
  }

  const request =
    options.request ??
    new Request("http://localhost/__vitest_server_fn__", {
      method,
      headers,
    });

  let executionResult: ServerFnExecutionResult | undefined;

  const handler = requestHandler(async () => {
    await runWithStartContext(
      {
        getRouter: async () => {
          throw new Error(
            "Router access is not available in this test harness",
          );
        },
        request,
        startOptions: {},
        contextAfterGlobalMiddlewares: options.context ?? {},
        executedRequestMiddlewares: new Set(),
      },
      async () => {
        const result = await compiledServerFn({
          method,
          data: options.data,
          headers: options.headers,
          context: options.context,
        });

        if (!isServerFnExecutionResult(result)) {
          throw new Error("Server function returned an unexpected payload");
        }

        executionResult = result;
      },
    );

    return new Response(null, { status: 204 });
  });

  const response = await handler(request, {});

  if (!executionResult) {
    throw new Error("Server function did not execute");
  }

  if (executionResult.error) {
    throw executionResult.error;
  }

  return {
    result: executionResult.result as T,
    context: executionResult.context,
    response,
  };
}

function isServerFnExecutionResult(
  value: unknown,
): value is ServerFnExecutionResult {
  if (typeof value !== "object" || value === null) {
    return false;
  }

  return "result" in value || "error" in value || "context" in value;
}
