import "vitest";

interface CustomMatchers<R = unknown> {}

declare module "vitest" {
  interface Assertion<T = any> {
    toBeUlid(): T;
    toBeDaysIntoFuture(days: number): T;
    toBeHoursIntoFuture(hours: number): T;
    toBeToken(length?: number): T;
    toBeNextjsRedirect(path: string): Promise<T>;
    toBeTanstackNotFound(): Promise<T>;
  }
  interface AsymmetricMatchersContaining {
    toBeUlid(): string;
    toBeNow<T extends Date | string>(): T;
    toBeDaysIntoFuture<T extends Date | string>(days: number): T;
    toBeHoursIntoFuture<T extends Date | string>(hours: number): T;
    toBeToken(length?: number): string;
  }
}

// This module is generated by the compiler
// and makes server fns available in the test environment.
declare module "#tanstack-start-server-fn-resolver" {
  export function getServerFnById(
    id: string,
  ): Promise<
    (opts: {
      method: "GET" | "POST";
      data?: unknown;
      headers?: HeadersInit;
      context?: Record<string, unknown>;
    }) => Promise<unknown>
  >;
}
