-- Generated by scripts/generate-sfm-gloss-migrations.js - do not edit.
-- Imports Indonesian interlinear glosses for the book of Jonah
-- (Jon) from src/data/sfm/32JONIGIHG.SFM, aligned to the `word`
-- rows of the platform database per src/data/sfm/gloss-alignment-report.txt:
--   * USFM-MORE: gloss-only tokens with no Hebrew word are dropped
--     (0 token(s))
--   * DB-MORE: un-glossed word rows are left without a gloss
--     (0 word(s))
--   * MULTI-WORD: the word rows covered by one gloss token become one
--     multi-word phrase (1 phrase(s) over 2 word(s))
--   * SPLIT-WORD: the tokens that gloss one word row are combined into
--     a single gloss (0 word(s))
-- DB verses of the book with no USFM gloss data are likewise left
-- un-glossed (see the report's data-completeness section).
--
-- Glosses are attributed to no user (phrase.created_by and
-- gloss.updated_by are NULL) with source IMPORT and state APPROVED.
--
-- Depends on:
-- 26-09-16-single-word-suggestion-counts.schema.sql (the fixed gloss
-- suggestion triggers this import relies on), which is why this
-- migration is dated after it.
--
-- 48 verses imported: 686 single-word
-- glosses, 1 multi-word phrases covering 2
-- words, 0 split-word glosses (688 words
-- glossed in total).

begin;

do $$
begin
  if not exists (select 1 from language where code = 'ind') then
    insert into language (id, code, english_name, local_name, translation_ids)
    values (generate_ulid(), 'ind', 'Indonesian', 'Bahasa Indonesia', '{}');
  end if;
end $$;

-- The phrase id sequence lags behind the max phrase id (phrases were
-- bulk-inserted with explicit ids), so resync it before creating phrases.
select setval('phrase_id_seq', greatest((select coalesce(max(id), 0) from phrase), (select last_value from phrase_id_seq)) + 1, false);

-- One row per gloss entry: `n` numbers the entries and `word_ids` holds
-- the word row(s) the gloss covers (a single id for a single-word gloss,
-- several ids in word order for a multi-word gloss / ketiv-qere pair).
create temp table _sfm_gloss (
  n int primary key,
  word_ids text[] not null,
  gloss text not null
) on commit drop;

insert into _sfm_gloss (n, word_ids, gloss) values
  (1, '{3200100101}', 'dan datanglah'),
  (2, '{3200100102}', 'firman'),
  (3, '{3200100103}', 'dari Yahweh'),
  (4, '{3200100104}', 'kepada'),
  (5, '{3200100105}', 'Yunus'),
  (6, '{3200100106}', 'anak'),
  (7, '{3200100107}', 'dari Amittai'),
  (8, '{3200100108}', '(cmp)'),
  (9, '{3200100201}', 'bangunlah'),
  (10, '{3200100202}', 'pergi'),
  (11, '{3200100203}', 'ke'),
  (12, '{3200100204}', 'Niniwe'),
  (13, '{3200100205}', 'kota'),
  (14, '{3200100206}', '(yang) besar'),
  (15, '{3200100207}', 'dan berserulah'),
  (16, '{3200100208}', 'terhadapnya'),
  (17, '{3200100209}', '(dm)'),
  (18, '{3200100210}', 'telah naik'),
  (19, '{3200100211}', 'kejahatan mereka'),
  (20, '{3200100212}', 'di hadapan-Ku'),
  (21, '{3200100301}', 'dan dia bangkit'),
  (22, '{3200100302}', 'Yunus'),
  (23, '{3200100303}', 'untuk melarikan diri'),
  (24, '{3200100304}', 'ke Tarsis'),
  (25, '{3200100305}', 'dari hadapan'),
  (26, '{3200100306}', 'Yahweh'),
  (27, '{3200100307}', 'dan ia turun ke'),
  (28, '{3200100308}', 'Yope'),
  (29, '{3200100309}', 'dan ia menemukan'),
  (30, '{3200100310}', 'sebuah kapal'),
  (31, '{3200100311}', '[yang] hendak pergi ke'),
  (32, '{3200100312}', 'Tarsis'),
  (33, '{3200100313}', 'dan dia memberikan'),
  (34, '{3200100314}', 'ongkosnya'),
  (35, '{3200100315}', 'dan dia turun'),
  (36, '{3200100316}', 'ke dalamnya'),
  (37, '{3200100317}', 'untuk pergi'),
  (38, '{3200100318}', 'bersama mereka'),
  (39, '{3200100319}', 'ke Tarsis'),
  (40, '{3200100320}', 'dari hadapan'),
  (41, '{3200100321}', 'Yahweh'),
  (42, '{3200100401}', 'dan Yahweh'),
  (43, '{3200100402}', 'melemparkan'),
  (44, '{3200100403}', 'angin'),
  (45, '{3200100404}', 'besar'),
  (46, '{3200100405}', 'ke'),
  (47, '{3200100406}', 'laut'),
  (48, '{3200100407}', 'dan terjadilah'),
  (49, '{3200100408}', 'badai'),
  (50, '{3200100409}', 'besar'),
  (51, '{3200100410}', 'di laut'),
  (52, '{3200100411}', 'dan kapal'),
  (53, '{3200100412}', 'itu pikir'),
  (54, '{3200100413}', 'akan hancur'),
  (55, '{3200100501}', 'dan mereka takut'),
  (56, '{3200100502}', 'para pelaut'),
  (57, '{3200100503}', 'dan mereka berteriak minta tolong'),
  (58, '{3200100504}', 'masing-masing'),
  (59, '{3200100505}', 'kepada'),
  (60, '{3200100506}', 'dewa-dewanya'),
  (61, '{3200100507}', 'dan mereka melemparkan'),
  (62, '{3200100508}', '(et)'),
  (63, '{3200100509}', 'barang-barang'),
  (64, '{3200100510}', 'yang'),
  (65, '{3200100511}', '[ada] di dalam kapal'),
  (66, '{3200100512}', 'ke dalam'),
  (67, '{3200100513}', 'laut'),
  (68, '{3200100514}', 'untuk meringankan'),
  (69, '{3200100515}', 'beban mereka'),
  (70, '{3200100516}', 'dan Yunus'),
  (71, '{3200100517}', 'ia telah turun'),
  (72, '{3200100518}', 'ke'),
  (73, '{3200100519}', 'bagian paling dalam'),
  (74, '{3200100520}', 'dari kapal itu'),
  (75, '{3200100521}', 'dan ia berbaring'),
  (76, '{3200100522}', 'dan ia tertidur'),
  (77, '{3200100601}', 'dan dia mendekat'),
  (78, '{3200100602}', 'kepadanya'),
  (79, '{3200100603}', 'kapten'),
  (80, '{3200100604}', 'dari para pelaut'),
  (81, '{3200100605}', 'dan dia berkata'),
  (82, '{3200100606}', 'kepadanya'),
  (83, '{3200100607}', 'mengapa'),
  (84, '{3200100608}', '[ada] padamu'),
  (85, '{3200100609}', 'tidur'),
  (86, '{3200100610}', 'bangunlah'),
  (87, '{3200100611}', 'berseru'),
  (88, '{3200100612}', 'kepada'),
  (89, '{3200100613}', 'Allahmu'),
  (90, '{3200100614}', 'mungkin'),
  (91, '{3200100615}', 'dia akan memperhatikan'),
  (92, '{3200100616}', 'Allah'),
  (93, '{3200100617}', 'kepada kita'),
  (94, '{3200100618}', 'dan tidak'),
  (95, '{3200100619}', 'kita akan binasa'),
  (96, '{3200100701}', 'dan mereka berkata'),
  (97, '{3200100702}', 'masing-masing'),
  (98, '{3200100703}', 'kepada'),
  (99, '{3200100704}', 'temannya'),
  (100, '{3200100705}', 'mari'),
  (101, '{3200100706}', 'dan mari kita membuang'),
  (102, '{3200100707}', 'undi'),
  (103, '{3200100708}', 'sehingga kita dapat mengetahui'),
  (104, '{3200100709}', 'karena siapa'),
  (105, '{3200100710}', 'malapetaka'),
  (106, '{3200100711}', '(yang) ini'),
  (107, '{3200100712}', '[terjadi] pada kita'),
  (108, '{3200100713}', 'dan mereka membuang'),
  (109, '{3200100714}', 'undi'),
  (110, '{3200100715}', 'dan jatuhlah'),
  (111, '{3200100716}', 'undian itu'),
  (112, '{3200100717}', 'pada'),
  (113, '{3200100718}', 'Yunus'),
  (114, '{3200100801}', 'dan mereka berkata'),
  (115, '{3200100802}', 'kepadanya'),
  (116, '{3200100803}', 'katakan'),
  (117, '{3200100804}', 'tolong'),
  (118, '{3200100805}', 'kepada kami'),
  (119, '{3200100806}', 'karena'),
  (120, '{3200100807}', 'siapa'),
  (121, '{3200100808}', 'malapetaka'),
  (122, '{3200100809}', '(yang) ini'),
  (123, '{3200100810}', '[terjadi] pada kita'),
  (124, '{3200100811}', 'apakah'),
  (125, '{3200100812}', '[adalah] pekerjaanmu'),
  (126, '{3200100813}', 'dan dari mana'),
  (127, '{3200100814}', 'engkau datang'),
  (128, '{3200100815}', 'apakah'),
  (129, '{3200100816}', '[adalah] negerimu'),
  (130, '{3200100817}', 'dan mana'),
  (131, '{3200100818}', 'dari ini'),
  (132, '{3200100819}', 'bangsa'),
  (133, '{3200100820}', '[adalah] engkau'),
  (134, '{3200100901}', 'dan dia berkata'),
  (135, '{3200100902}', 'kepada mereka'),
  (136, '{3200100903}', '[adalah] seorang Ibrani'),
  (137, '{3200100904}', 'aku'),
  (138, '{3200100905}', 'dan (et)'),
  (139, '{3200100906}', 'Yahweh'),
  (140, '{3200100907}', 'Allah'),
  (141, '{3200100908}', 'dari langit'),
  (142, '{3200100909}', 'aku'),
  (143, '{3200100910}', '[yang] takuti'),
  (144, '{3200100911}', 'yang'),
  (145, '{3200100912}', 'membuat'),
  (146, '{3200100913}', '(et)'),
  (147, '{3200100914}', 'laut'),
  (148, '{3200100915}', 'dan (et)'),
  (149, '{3200100916}', 'daratan'),
  (150, '{3200101001}', 'dan mereka takut'),
  (151, '{3200101002}', 'orang-orang'),
  (152, '{3200101003}', 'ketakutan'),
  (153, '{3200101004}', 'besar'),
  (154, '{3200101005}', 'dan mereka berkata'),
  (155, '{3200101006}', 'kepadanya'),
  (156, '{3200101007}', 'apakah'),
  (157, '{3200101008}', 'ini'),
  (158, '{3200101009}', 'telah kau lakukan'),
  (159, '{3200101010}', '(dm)'),
  (160, '{3200101011}', 'mereka tahu'),
  (161, '{3200101012}', 'orang-orang'),
  (162, '{3200101013}', '(dm) bahwa'),
  (163, '{3200101014}', 'dari hadapan'),
  (164, '{3200101015}', 'Yahweh'),
  (165, '{3200101016}', 'dia'),
  (166, '{3200101017}', 'sedang melarikan diri'),
  (167, '{3200101018}', '(dm)'),
  (168, '{3200101019}', 'dia telah memberitahukan'),
  (169, '{3200101020}', 'kepada mereka'),
  (170, '{3200101101}', 'dan mereka berkata'),
  (171, '{3200101102}', 'kepadanya'),
  (172, '{3200101103}', 'apakah'),
  (173, '{3200101104}', 'yang akan kita lakukan'),
  (174, '{3200101105}', 'kepadamu'),
  (175, '{3200101106}', 'sehingga akan tenang'),
  (176, '{3200101107}', 'laut'),
  (177, '{3200101108}', 'dari atas kami'),
  (178, '{3200101109}', '(dm)'),
  (179, '{3200101110}', 'laut'),
  (180, '{3200101111}', '[sedang] bergerak'),
  (181, '{3200101112}', 'dan mengamuk'),
  (182, '{3200101201}', 'dan dia berkata'),
  (183, '{3200101202}', 'kepada mereka'),
  (184, '{3200101203}', 'angkatlah aku'),
  (185, '{3200101204}', 'dan lemparkan aku'),
  (186, '{3200101205}', 'ke dalam'),
  (187, '{3200101206}', 'laut'),
  (188, '{3200101207}', 'dan akan tenang'),
  (189, '{3200101208}', 'laut'),
  (190, '{3200101209}', 'dari atas kamu'),
  (191, '{3200101210}', '(dm)'),
  (192, '{3200101211}', '[aku] tahu'),
  (193, '{3200101212}', 'aku'),
  (194, '{3200101213}', '(dm) bahwa'),
  (195, '{3200101214}', 'karena akulah'),
  (196, '{3200101215}', 'badai'),
  (197, '{3200101216}', '(yang) besar'),
  (198, '{3200101217}', '(yang) ini'),
  (199, '{3200101218}', '[ada] atas kamu'),
  (200, '{3200101301}', 'dan mereka mendayung'),
  (201, '{3200101302}', 'orang-orang'),
  (202, '{3200101303}', 'untuk kembali'),
  (203, '{3200101304}', 'ke'),
  (204, '{3200101305}', 'daratan'),
  (205, '{3200101306}', 'dan tidak'),
  (206, '{3200101307}', 'mereka mampu'),
  (207, '{3200101308}', '(dm)'),
  (208, '{3200101309}', 'laut'),
  (209, '{3200101310}', '[sedang] bergerak'),
  (210, '{3200101311}', 'dan mengamuk'),
  (211, '{3200101312}', 'pada mereka'),
  (212, '{3200101401}', 'dan mereka berseru'),
  (213, '{3200101402}', 'kepada'),
  (214, '{3200101403}', 'Yahweh'),
  (215, '{3200101404}', 'dan mereka berkata'),
  (216, '{3200101405}', 'tolong!'),
  (217, '{3200101406}', 'Ya Yahweh'),
  (218, '{3200101407}', 'janganlah'),
  (219, '{3200101408}', 'kiranya'),
  (220, '{3200101409}', 'biarkan kami binasa'),
  (221, '{3200101410}', 'karena nyawa'),
  (222, '{3200101411}', 'dari orang'),
  (223, '{3200101412}', '(yang) ini'),
  (224, '{3200101413}', 'dan janganlah'),
  (225, '{3200101414}', 'timpakan'),
  (226, '{3200101415}', 'pada kami'),
  (227, '{3200101416}', 'darah'),
  (228, '{3200101417}', 'orang tak bersalah'),
  (229, '{3200101418}', '(dm)'),
  (230, '{3200101419}', 'Engkau'),
  (231, '{3200101420}', 'Ya Yahweh'),
  (232, '{3200101421}', 'seperti'),
  (233, '{3200101422}', 'yang Engkau kehendaki'),
  (234, '{3200101423}', 'Engkau telah melakukan'),
  (235, '{3200101501}', 'dan mereka mengangkat'),
  (236, '{3200101502}', '(et)'),
  (237, '{3200101503}', 'Yunus'),
  (238, '{3200101504}', 'dan mereka melemparkannya'),
  (239, '{3200101505}', 'ke dalam'),
  (240, '{3200101506}', 'laut'),
  (241, '{3200101507}', 'dan berhentilah'),
  (242, '{3200101508}', 'laut'),
  (243, '{3200101509}', 'dari amukannya'),
  (244, '{3200101601}', 'dan mereka takut'),
  (245, '{3200101602}', 'orang-orang'),
  (246, '{3200101603}', 'ketakutan'),
  (247, '{3200101604}', 'besar'),
  (248, '{3200101605}', 'akan'),
  (249, '{3200101606}', 'Yahweh'),
  (250, '{3200101607}', 'dan mereka mempersembahkan'),
  (251, '{3200101608}', 'korban'),
  (252, '{3200101609}', 'kepada Yahweh'),
  (253, '{3200101610}', 'dan mereka bernazar'),
  (254, '{3200101611}', 'nazar'),
  (255, '{3200101701}', 'dan Dia menentukan'),
  (256, '{3200101702}', 'Yahweh'),
  (257, '{3200101703}', 'seekor ikan'),
  (258, '{3200101704}', 'besar'),
  (259, '{3200101705}', 'untuk menelan'),
  (260, '{3200101706}', '(et)'),
  (261, '{3200101707}', 'Yunus'),
  (262, '{3200101708}', 'dan dia berada'),
  (263, '{3200101709}', 'Yunus'),
  (264, '{3200101710}', 'di dalam perut'),
  (265, '{3200101711}', 'dari ikan itu'),
  (266, '{3200101712}', 'tiga'),
  (267, '{3200101713}', 'hari'),
  (268, '{3200101714}', 'dan tiga'),
  (269, '{3200101715}', 'malam'),
  (270, '{3200200101}', 'dan dia berdoa'),
  (271, '{3200200102}', 'Yunus'),
  (272, '{3200200103}', 'kepada'),
  (273, '{3200200104}', 'Yahweh'),
  (274, '{3200200105}', 'Allahnya'),
  (275, '{3200200106}', 'dari dalam perut'),
  (276, '{3200200107}', 'dari ikan itu'),
  (277, '{3200200201}', 'dan dia berkata'),
  (278, '{3200200202}', 'aku berseru'),
  (279, '{3200200203}', 'dari kesesakan'),
  (280, '{3200200204}', 'aku'),
  (281, '{3200200205}', 'kepada'),
  (282, '{3200200206}', 'Yahweh'),
  (283, '{3200200207}', 'dan Dia menjawab aku'),
  (284, '{3200200208}', 'dari perut'),
  (285, '{3200200209}', 'dunia orang mati'),
  (286, '{3200200210}', 'aku berteriak minta tolong'),
  (287, '{3200200211}', 'Engkau mendengar'),
  (288, '{3200200212}', 'suaraku'),
  (289, '{3200200301}', 'dan Engkau telah melemparkan aku'),
  (290, '{3200200302}', '[ke] dalam'),
  (291, '{3200200303}', 'di [dalam] hati'),
  (292, '{3200200304}', 'dari lautan'),
  (293, '{3200200305}', 'dan arus'),
  (294, '{3200200306}', 'mengelilingi aku'),
  (295, '{3200200307}', 'semua'),
  (296, '{3200200308}', 'gelombang pemecahMu'),
  (297, '{3200200309}', 'dan ombak-Mu'),
  (298, '{3200200310}', 'di atasku'),
  (299, '{3200200311}', 'mereka telah berlalu'),
  (300, '{3200200401}', 'dan aku'),
  (301, '{3200200402}', 'aku berkata'),
  (302, '{3200200403}', 'aku telah diusir'),
  (303, '{3200200404}', 'dari hadapan'),
  (304, '{3200200405}', 'mata-Mu'),
  (305, '{3200200406}', 'namun'),
  (306, '{3200200407}', 'aku akan kembali'),
  (307, '{3200200408}', 'memandang'),
  (308, '{3200200409}', 'ke'),
  (309, '{3200200410}', 'bait'),
  (310, '{3200200411}', 'dari kekudusan-Mu'),
  (311, '{3200200501}', 'telah mengelilingi aku'),
  (312, '{3200200502}', 'air'),
  (313, '{3200200503}', 'sampai'),
  (314, '{3200200504}', '[ke] leher'),
  (315, '{3200200505}', 'samudera'),
  (316, '{3200200506}', 'mengelilingi aku'),
  (317, '{3200200507}', 'rumput laut'),
  (318, '{3200200508}', '[ter] lilit'),
  (319, '{3200200509}', 'di kepalaku'),
  (320, '{3200200601}', 'ke dasar'),
  (321, '{3200200602}', 'gunung-gunung'),
  (322, '{3200200603}', 'aku turun'),
  (323, '{3200200604}', 'bumi'),
  (324, '{3200200605}', 'palang-palangnya'),
  (325, '{3200200606}', '[ada] di belakangku'),
  (326, '{3200200607}', 'selamanya'),
  (327, '{3200200608}', 'dan Engkau mengangkat'),
  (328, '{3200200609}', 'dari [lubang] kubur'),
  (329, '{3200200610}', 'hidupku'),
  (330, '{3200200611}', 'Ya Yahweh'),
  (331, '{3200200612}', 'Allahku'),
  (332, '{3200200701}', 'ketika lemah'),
  (333, '{3200200702}', 'dalam diriku'),
  (334, '{3200200703}', 'jiwaku'),
  (335, '{3200200704}', '(akan)'),
  (336, '{3200200705}', 'Yahweh'),
  (337, '{3200200706}', 'aku ingat'),
  (338, '{3200200707}', 'dan sampailah'),
  (339, '{3200200708}', 'kepada-Mu'),
  (340, '{3200200709}', 'doaku'),
  (341, '{3200200710}', 'ke'),
  (342, '{3200200711}', 'bait'),
  (343, '{3200200712}', 'dari kekudusan-Mu'),
  (344, '{3200200801}', '[mereka yang] memperhatikan'),
  (345, '{3200200802}', 'kesia-siaan'),
  (346, '{3200200803}', 'ketiadaan'),
  (347, '{3200200804}', 'kesetiaan mereka'),
  (348, '{3200200805}', 'mereka tinggalkan'),
  (349, '{3200200901}', 'dan aku'),
  (350, '{3200200902}', 'dengan suara'),
  (351, '{3200200903}', 'ucapan syukur'),
  (352, '{3200200904}', 'aku akan berkurban'),
  (353, '{3200200905}', 'kepada-Mu'),
  (354, '{3200200906}', '[apa] yang'),
  (355, '{3200200907}', 'aku telah nazarkan'),
  (356, '{3200200908}', 'aku akan bayar'),
  (357, '{3200200909}', 'keselamatan'),
  (358, '{3200200910}', '[milik] Yahweh'),
  (359, '{3200201001}', 'dan Dia berfirman'),
  (360, '{3200201002}', 'Yahweh'),
  (361, '{3200201003}', 'kepada ikan itu'),
  (362, '{3200201004}', 'dan ikan itu memuntahkan'),
  (363, '{3200201005}', '(et)'),
  (364, '{3200201006}', 'Yunus'),
  (365, '{3200201007}', 'ke'),
  (366, '{3200201008}', 'daratan'),
  (367, '{3200300101}', 'dan datanglah'),
  (368, '{3200300102}', 'firman'),
  (369, '{3200300103}', 'dari Yahweh'),
  (370, '{3200300104}', 'kepada'),
  (371, '{3200300105}', 'Yunus'),
  (372, '{3200300106}', 'untuk [kali] kedua'),
  (373, '{3200300107}', '(cmp)'),
  (374, '{3200300201}', 'bangunlah'),
  (375, '{3200300202}', 'pergi'),
  (376, '{3200300203}', 'ke'),
  (377, '{3200300204}', 'Niniwe'),
  (378, '{3200300205}', 'kota'),
  (379, '{3200300206}', '(yang) besar'),
  (380, '{3200300207}', 'dan serukanlah'),
  (381, '{3200300208}', 'terhadapnya'),
  (382, '{3200300209}', '(et)'),
  (383, '{3200300210}', 'pesan'),
  (384, '{3200300211}', 'yang'),
  (385, '{3200300212}', 'Aku'),
  (386, '{3200300213}', '[sedang] katakan'),
  (387, '{3200300214}', 'kepadamu'),
  (388, '{3200300301}', 'dan dia bangkit'),
  (389, '{3200300302}', 'Yunus'),
  (390, '{3200300303}', 'dan ia pergi'),
  (391, '{3200300304}', 'ke'),
  (392, '{3200300305}', 'Niniwe'),
  (393, '{3200300306}', 'sesuai dengan firman'),
  (394, '{3200300307}', 'dari Yahweh'),
  (395, '{3200300308}', 'dan Niniwe'),
  (396, '{3200300309}', 'adalah'),
  (397, '{3200300310}', 'sebuah kota'),
  (398, '{3200300311}', 'besar'),
  (399, '{3200300312}', 'bagi Allah'),
  (400, '{3200300313}', 'perjalanan'),
  (401, '{3200300314}', 'dari tiga'),
  (402, '{3200300315}', 'hari'),
  (403, '{3200300401}', 'dan dia mulai'),
  (404, '{3200300402}', 'Yunus'),
  (405, '{3200300403}', 'berjalan'),
  (406, '{3200300404}', 'di kota'),
  (407, '{3200300405}', 'perjalanan'),
  (408, '{3200300406}', 'sehari'),
  (409, '{3200300407}', 'satu'),
  (410, '{3200300408}', 'dan ia menyerukan'),
  (411, '{3200300409}', 'dan dia berkata'),
  (412, '{3200300410}', 'dalam'),
  (413, '{3200300411}', 'empat puluh'),
  (414, '{3200300412}', 'hari'),
  (415, '{3200300413}', 'Niniwe'),
  (416, '{3200300414}', '[akan] dihancurkan'),
  (417, '{3200300501}', 'dan mereka percaya'),
  (418, '{3200300502}', 'orang-orang'),
  (419, '{3200300503}', 'dari Niniwe'),
  (420, '{3200300504}', 'kepada Allah'),
  (421, '{3200300505}', 'dan mereka mengumumkan'),
  (422, '{3200300506}', 'puasa'),
  (423, '{3200300507}', 'dan mereka mengenakan'),
  (424, '{3200300508}', 'kain kabung'),
  (425, '{3200300509}', 'dari yang besar'),
  (426, '{3200300510}', 'dan sampai'),
  (427, '{3200300511}', 'yang kecil'),
  (428, '{3200300601}', 'dan sampailah'),
  (429, '{3200300602}', 'berita'),
  (430, '{3200300603}', 'kepada'),
  (431, '{3200300604}', 'raja'),
  (432, '{3200300605}', 'dari Niniwe'),
  (433, '{3200300606}', 'dan dia bangkit'),
  (434, '{3200300607}', 'dari takhtanya'),
  (435, '{3200300608}', 'dan dia menanggalkan'),
  (436, '{3200300609}', 'jubahnya'),
  (437, '{3200300610}', 'dari tubuhnya'),
  (438, '{3200300611}', 'dan dia menyelubungi'),
  (439, '{3200300612}', 'kain kabung'),
  (440, '{3200300613}', 'dan dia duduk'),
  (441, '{3200300614}', 'di atas'),
  (442, '{3200300615}', 'abu'),
  (443, '{3200300701}', 'dan dia membuat pengumuman'),
  (444, '{3200300702}', 'dan dia berkata'),
  (445, '{3200300703}', 'di Niniwe'),
  (446, '{3200300704}', 'dari keputusan'),
  (447, '{3200300705}', 'dari raja'),
  (448, '{3200300706}', 'dan para [pejabat] besarnya'),
  (449, '{3200300707}', '(cmp)'),
  (450, '{3200300708}', 'rakyat'),
  (451, '{3200300709}', 'dan ternak'),
  (452, '{3200300710}', 'sapi'),
  (453, '{3200300711}', 'dan domba'),
  (454, '{3200300712}', 'tidak'),
  (455, '{3200300713}', 'boleh mencicipi'),
  (456, '{3200300714}', 'apapun'),
  (457, '{3200300715}', 'tidak'),
  (458, '{3200300716}', 'boleh merumput'),
  (459, '{3200300717}', 'dan air'),
  (460, '{3200300718}', 'tidak'),
  (461, '{3200300719}', 'boleh minum'),
  (462, '{3200300801}', 'dan hendaklah menutupi diri'),
  (463, '{3200300802}', 'kain kabung'),
  (464, '{3200300803}', 'manusia'),
  (465, '{3200300804}', 'dan binatang'),
  (466, '{3200300805}', 'dan biarlah mereka berseru'),
  (467, '{3200300806}', 'kepada'),
  (468, '{3200300807}', 'Allah'),
  (469, '{3200300808}', 'dengan kuat'),
  (470, '{3200300809}', 'dan biarlah mereka berbalik'),
  (471, '{3200300810}', 'setiap orang'),
  (472, '{3200300811}', 'dari jalannya'),
  (473, '{3200300812}', '(yang) jahat'),
  (474, '{3200300813}', 'dan dari'),
  (475, '{3200300814}', 'kekerasan'),
  (476, '{3200300815}', 'yang'),
  (477, '{3200300816}', '[ada] di tangan mereka'),
  (478, '{3200300901}', 'siapa'),
  (479, '{3200300902}', '[yang] tahu'),
  (480, '{3200300903}', 'mungkin Dia akan berbalik'),
  (481, '{3200300904}', 'dan Dia akan menyesal'),
  (482, '{3200300905}', 'Allah'),
  (483, '{3200300906}', 'dan Dia akan berbalik'),
  (484, '{3200300907}', 'dari nyala'),
  (485, '{3200300908}', 'dari murka-Nya'),
  (486, '{3200300909}', 'dan tidak'),
  (487, '{3200300910}', 'kita akan binasa'),
  (488, '{3200301001}', 'dan Dia melihat'),
  (489, '{3200301002}', 'Allah'),
  (490, '{3200301003}', '(et)'),
  (491, '{3200301004}', 'perbuatan mereka'),
  (492, '{3200301005}', '(dm) bahwa'),
  (493, '{3200301006}', 'mereka berbalik'),
  (494, '{3200301007}', 'dari jalan mereka'),
  (495, '{3200301008}', '(yang) jahat'),
  (496, '{3200301009}', 'dan Dia menyesal'),
  (497, '{3200301010}', 'Allah'),
  (498, '{3200301011}', 'atas'),
  (499, '{3200301012}', 'kejahatan'),
  (500, '{3200301013}', 'yang'),
  (501, '{3200301014}', 'telah Dia katakan'),
  (502, '{3200301015}', 'untuk dilakukan'),
  (503, '{3200301016}', 'kepada mereka'),
  (504, '{3200301017}', 'dan tidak'),
  (505, '{3200301018}', 'Dia melakukannya'),
  (506, '{3200400101}', 'dan hal itu menyusahkan'),
  (507, '{3200400102}', 'bagi'),
  (508, '{3200400103}', 'Yunus'),
  (509, '{3200400104}', 'kesusahan'),
  (510, '{3200400105}', 'besar'),
  (511, '{3200400106,3200400107}', 'dan dia marah'),
  (512, '{3200400201}', 'dan dia berdoa'),
  (513, '{3200400202}', 'kepada'),
  (514, '{3200400203}', 'Yahweh'),
  (515, '{3200400204}', 'dan dia berkata'),
  (516, '{3200400205}', 'ah!'),
  (517, '{3200400206}', 'Ya Yahweh'),
  (518, '{3200400207}', 'bukankah'),
  (519, '{3200400208}', '[adalah] ini'),
  (520, '{3200400209}', 'perkataanku'),
  (521, '{3200400210}', 'ketika'),
  (522, '{3200400211}', 'aku masih'),
  (523, '{3200400212}', 'di'),
  (524, '{3200400213}', 'negeriku sendiri'),
  (525, '{3200400214}', 'karena'),
  (526, '{3200400215}', 'itu'),
  (527, '{3200400216}', 'aku segera'),
  (528, '{3200400217}', 'untuk melarikan diri'),
  (529, '{3200400218}', 'ke Tarsis'),
  (530, '{3200400219}', '(dm)'),
  (531, '{3200400220}', 'aku tahu'),
  (532, '{3200400221}', '(dm) bahwa'),
  (533, '{3200400222}', 'Engkau'),
  (534, '{3200400223}', '[adalah] Allah'),
  (535, '{3200400224}', 'pengasih'),
  (536, '{3200400225}', 'dan penyayang'),
  (537, '{3200400226}', 'panjang'),
  (538, '{3200400227}', 'sabar'),
  (539, '{3200400228}', 'dan berlimpah'),
  (540, '{3200400229}', 'kasih setia'),
  (541, '{3200400230}', 'dan [yang] menyesal'),
  (542, '{3200400231}', 'atas'),
  (543, '{3200400232}', 'keburukan'),
  (544, '{3200400301}', 'dan sekarang'),
  (545, '{3200400302}', 'Ya Yahweh'),
  (546, '{3200400303}', 'ambillah'),
  (547, '{3200400304}', 'kiranya'),
  (548, '{3200400305}', '(et)'),
  (549, '{3200400306}', 'nyawaku'),
  (550, '{3200400307}', 'dariku'),
  (551, '{3200400308}', '(dm)'),
  (552, '{3200400309}', '[lebih] baik'),
  (553, '{3200400310}', 'kematianku'),
  (554, '{3200400311}', 'daripada hidupku'),
  (555, '{3200400401}', 'dan Dia berkata'),
  (556, '{3200400402}', 'Yahweh'),
  (557, '{3200400403}', 'pantaskah'),
  (558, '{3200400404}', 'marah'),
  (559, '{3200400405}', 'engkau'),
  (560, '{3200400501}', 'dan dia keluar'),
  (561, '{3200400502}', 'Yunus'),
  (562, '{3200400503}', 'dari'),
  (563, '{3200400504}', 'kota'),
  (564, '{3200400505}', 'dan dia duduk'),
  (565, '{3200400506}', 'di sebelah timur'),
  (566, '{3200400507}', 'dari kota itu'),
  (567, '{3200400508}', 'dan dia membuat'),
  (568, '{3200400509}', 'bagi dirinya'),
  (569, '{3200400510}', 'di sana'),
  (570, '{3200400511}', 'sebuah pondok'),
  (571, '{3200400512}', 'dan dia duduk'),
  (572, '{3200400513}', 'di bawahnya'),
  (573, '{3200400514}', 'di tempat teduh'),
  (574, '{3200400515}', 'sampai'),
  (575, '{3200400516}', 'yang'),
  (576, '{3200400517}', 'dia melihat'),
  (577, '{3200400518}', 'apa'),
  (578, '{3200400519}', 'yang akan terjadi'),
  (579, '{3200400520}', 'pada kota itu'),
  (580, '{3200400601}', 'dan Dia menentukan'),
  (581, '{3200400602}', 'Yahweh'),
  (582, '{3200400603}', 'Allah'),
  (583, '{3200400604}', 'sebatang tanaman'),
  (584, '{3200400605}', 'dan tanaman itu tumbuh'),
  (585, '{3200400606}', '(hingga) di atas'),
  (586, '{3200400607}', '(menutupi) Yunus'),
  (587, '{3200400608}', 'untuk menjadi'),
  (588, '{3200400609}', 'naungan'),
  (589, '{3200400610}', 'di atas'),
  (590, '{3200400611}', 'kepalanya'),
  (591, '{3200400612}', 'untuk melepaskan'),
  (592, '{3200400613}', 'dia'),
  (593, '{3200400614}', 'dari kesusahannya'),
  (594, '{3200400615}', 'dan dia bersukacita'),
  (595, '{3200400616}', 'Yunus'),
  (596, '{3200400617}', 'atas'),
  (597, '{3200400618}', 'tanaman itu'),
  (598, '{3200400619}', 'sukacita'),
  (599, '{3200400620}', 'besar'),
  (600, '{3200400701}', 'dan Dia menentukan'),
  (601, '{3200400702}', 'Allah'),
  (602, '{3200400703}', 'seekor ulat'),
  (603, '{3200400704}', 'ketika terbit'),
  (604, '{3200400705}', 'fajar'),
  (605, '{3200400706}', 'keesokan harinya'),
  (606, '{3200400707}', 'dan ulat itu menyerang'),
  (607, '{3200400708}', '(et)'),
  (608, '{3200400709}', 'tanaman itu'),
  (609, '{3200400710}', 'dan tanaman itu layu'),
  (610, '{3200400801}', 'dan terjadi'),
  (611, '{3200400802}', 'ketika terbit'),
  (612, '{3200400803}', 'matahari'),
  (613, '{3200400804}', 'dan Dia menentukan'),
  (614, '{3200400805}', 'Allah'),
  (615, '{3200400806}', 'angin'),
  (616, '{3200400807}', 'timur'),
  (617, '{3200400808}', 'yang panas'),
  (618, '{3200400809}', 'dan memukul'),
  (619, '{3200400810}', 'matahari'),
  (620, '{3200400811}', 'pada'),
  (621, '{3200400812}', 'kepala'),
  (622, '{3200400813}', 'Yunus'),
  (623, '{3200400814}', 'dan dia lemah'),
  (624, '{3200400815}', 'dan dia meminta'),
  (625, '{3200400816}', 'agar'),
  (626, '{3200400817}', 'hidupnya'),
  (627, '{3200400818}', 'berakhir'),
  (628, '{3200400819}', 'dan dia berkata'),
  (629, '{3200400820}', '[lebih] baik'),
  (630, '{3200400821}', 'kematianku'),
  (631, '{3200400822}', 'daripada hidupku'),
  (632, '{3200400901}', 'dan Dia berkata'),
  (633, '{3200400902}', 'Allah'),
  (634, '{3200400903}', 'kepada'),
  (635, '{3200400904}', 'Yunus'),
  (636, '{3200400905}', 'pantaskah'),
  (637, '{3200400906}', 'marah'),
  (638, '{3200400907}', 'engkau'),
  (639, '{3200400908}', 'karena'),
  (640, '{3200400909}', 'tanaman itu'),
  (641, '{3200400910}', 'dan dia berkata'),
  (642, '{3200400911}', 'pantas'),
  (643, '{3200400912}', 'marah'),
  (644, '{3200400913}', 'aku'),
  (645, '{3200400914}', 'sampai'),
  (646, '{3200400915}', 'mati'),
  (647, '{3200401001}', 'dan Dia berkata'),
  (648, '{3200401002}', 'Yahweh'),
  (649, '{3200401003}', 'engkau'),
  (650, '{3200401004}', 'merasa sayang'),
  (651, '{3200401005}', 'pada'),
  (652, '{3200401006}', 'tanaman itu'),
  (653, '{3200401007}', 'yang'),
  (654, '{3200401008}', 'tidak'),
  (655, '{3200401009}', 'engkau susah payahkan'),
  (656, '{3200401010}', 'untuknya'),
  (657, '{3200401011}', 'dan tidak'),
  (658, '{3200401012}', 'engkau tumbuhkan'),
  (659, '{3200401013}', 'yang'),
  (660, '{3200401014}', 'dalam semalam'),
  (661, '{3200401015}', 'tumbuh'),
  (662, '{3200401016}', 'dan dalam'),
  (663, '{3200401017}', 'semalam'),
  (664, '{3200401018}', 'binasa'),
  (665, '{3200401101}', 'dan Aku'),
  (666, '{3200401102}', 'tidakkah'),
  (667, '{3200401103}', 'akan Aku merasa sayang'),
  (668, '{3200401104}', 'pada'),
  (669, '{3200401105}', 'Niniwe'),
  (670, '{3200401106}', 'kota'),
  (671, '{3200401107}', '(yang) besar'),
  (672, '{3200401108}', 'yang'),
  (673, '{3200401109}', 'ada'),
  (674, '{3200401110}', 'di dalamnya'),
  (675, '{3200401111}', 'banyak'),
  (676, '{3200401112}', 'lebih dari dua tambah'),
  (677, '{3200401113}', 'sepuluh'),
  (678, '{3200401114}', 'laksa'),
  (679, '{3200401115}', 'orang'),
  (680, '{3200401116}', 'yang'),
  (681, '{3200401117}', 'tidak'),
  (682, '{3200401118}', 'dapat membedakan'),
  (683, '{3200401119}', 'antara'),
  (684, '{3200401120}', 'tangan kanan'),
  (685, '{3200401121}', 'dan tangan kirinya'),
  (686, '{3200401122}', 'dan ternak'),
  (687, '{3200401123}', 'banyak');

create temp table _sfm_unit_word on commit drop as
select g.n, w.word_id
from _sfm_gloss g
cross join unnest(g.word_ids) as w(word_id);

do $$
begin
  -- every word id must be a word row of this book
  if exists (
    select 1 from _sfm_unit_word as uw
    where not exists (
      select 1 from word as w
      join verse as v on v.id = w.verse_id
      where w.id = uw.word_id and v.book_id = 32
    )
  ) then
    raise exception 'Unknown or non-Jon word id in import data';
  end if;

  -- a word row must not be imported by two gloss entries
  if exists (
    select 1 from _sfm_unit_word group by word_id having count(*) > 1
  ) then
    raise exception 'Word id imported by more than one gloss entry';
  end if;
end $$;

-- A word may already be covered by an active Indonesian phrase (a re-run
-- of this migration, or phrases created outside this import). A gloss
-- entry must then be fully covered by one shared phrase; a partially
-- covered entry is rejected instead of silently split.
create temp table _sfm_covered on commit drop as
select uw.n, uw.word_id, pw.phrase_id
from _sfm_unit_word as uw
join phrase_word as pw on pw.word_id = uw.word_id
join phrase as p on p.id = pw.phrase_id
where p.language_id = (select id from language where code = 'ind')
  and p.deleted_at is null;

do $$
begin
  if exists (
    select 1 from _sfm_covered group by n, word_id having count(*) > 1
  ) then
    raise exception 'Imported word covered by several active Indonesian phrases';
  end if;

  if exists (
    select 1
    from _sfm_unit_word as uw
    left join _sfm_covered as c on c.n = uw.n and c.word_id = uw.word_id
    group by uw.n
    having (count(c.phrase_id) > 0 and count(c.phrase_id) <> count(*))
       or count(distinct c.phrase_id) > 1
  ) then
    raise exception 'Gloss entry only partially covered by an existing phrase';
  end if;
end $$;

-- Create one phrase per uncovered gloss entry.
create temp table _sfm_new_phrase (n int primary key, id int not null) on commit drop;

with new_entry as (
  select g.n from _sfm_gloss as g
  where not exists (select 1 from _sfm_covered as c where c.n = g.n)
),
new_phrase as (
  insert into phrase (language_id, created_at, created_by)
  select (select id from language where code = 'ind'), now(), null
  from new_entry
  returning id
)
insert into _sfm_new_phrase (n, id)
select ne.n, np.id
from (select n, row_number() over (order by n) as rn from new_entry) as ne
join (select id, row_number() over (order by id) as rn from new_phrase) as np
  on np.rn = ne.rn;

insert into phrase_word (phrase_id, word_id)
select np.id, uw.word_id
from _sfm_new_phrase as np
join _sfm_unit_word as uw on uw.n = np.n;

create temp table _sfm_target on commit drop as
select
  g.n,
  coalesce(
    (select c.phrase_id from _sfm_covered as c where c.n = g.n limit 1),
    (select np.id from _sfm_new_phrase as np where np.n = g.n)
  ) as phrase_id,
  g.gloss as new_gloss
from _sfm_gloss as g;

do $$
begin
  if exists (select 1 from _sfm_target where phrase_id is null) then
    raise exception 'Gloss entry without a phrase';
  end if;

  if exists (
    select 1
    from _sfm_target as t
    join _sfm_unit_word as uw on uw.n = t.n
    where not exists (
      select 1 from phrase_word as pw
      where pw.phrase_id = t.phrase_id and pw.word_id = uw.word_id
    )
  ) then
    raise exception 'Phrase does not cover all words of its gloss entry';
  end if;

  if (select count(*) from _sfm_target) <> (select count(*) from _sfm_gloss) then
    raise exception 'Target phrase row count does not match gloss entry count';
  end if;
end $$;

-- Upsert the glosses. The (fixed) gloss suggestion triggers keep
-- lemma_form_suggestion in sync for single-word phrases (multi-word
-- phrases carry no suggestion count); unchanged rows are skipped so
-- re-running the migration fires no triggers at all.
insert into gloss (phrase_id, gloss, state, source, updated_at, updated_by)
select phrase_id, new_gloss, 'APPROVED', 'IMPORT', now(), null
from _sfm_target
on conflict (phrase_id) do update
set
  gloss = excluded.gloss,
  state = 'APPROVED',
  source = 'IMPORT',
  updated_at = excluded.updated_at,
  updated_by = null
where gloss.gloss is distinct from excluded.gloss
   or gloss.state <> 'APPROVED'
   or gloss.source <> 'IMPORT';

commit;
