import { config, library } from "@fortawesome/fontawesome-svg-core";
import * as FaSolid from "@fortawesome/free-solid-svg-icons";
import * as FaBrands from "@fortawesome/free-brands-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

export const Icon = FontAwesomeIcon;

config.autoAddCss = false;

library.add(
  FaBrands.faGithub,
  FaBrands.faGoogle,
  FaSolid.faShareFromSquare,
  FaSolid.faDatabase,
  FaSolid.faRobot,
  FaSolid.faCirclePlay,
  FaSolid.faClipboardCheck,
  FaSolid.faPause,
  FaSolid.faPlay,
  FaSolid.faCaretUp,
  FaSolid.faCaretDown,
  FaSolid.faCaretLeft,
  FaSolid.faCaretRight,
  FaSolid.faUser,
  FaSolid.faClose,
  FaSolid.faPlus,
  FaSolid.faCheck,
  FaSolid.faCheckCircle,
  FaSolid.faArrowsRotate,
  FaSolid.faArrowUp,
  FaSolid.faArrowDown,
  FaSolid.faArrowLeft,
  FaSolid.faArrowRight,
  FaSolid.faRightFromBracket,
  FaSolid.faExclamationCircle,
  FaSolid.faExclamationTriangle,
  FaSolid.faFileArrowDown,
  FaSolid.faFileImport,
  FaSolid.faDownload,
  FaSolid.faChevronUp,
  FaSolid.faChevronDown,
  FaSolid.faChevronRight,
  FaSolid.faBold,
  FaSolid.faItalic,
  FaSolid.faStrikethrough,
  FaSolid.faListUl,
  FaSolid.faListOl,
  FaSolid.faIndent,
  FaSolid.faOutdent,
  FaSolid.faArrowRotateLeft,
  FaSolid.faLanguage,
  FaSolid.faUser,
  FaSolid.faGear,
  FaSolid.faSliders,
  FaSolid.faAlignLeft,
  FaSolid.faAlignRight,
  FaSolid.faExternalLink,
  FaSolid.faStickyNote,
  FaSolid.faSave,
  FaSolid.faLink,
  FaSolid.faUnlink,
  FaSolid.faBars,
  FaSolid.faQuestionCircle,
  FaSolid.faFeather,
  FaSolid.faBookOpen,
  FaSolid.faForwardStep,
  FaSolid.faBackwardStep,
);
