import * as fs from "fs";
import * as path from "path";
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import { getSchemaModules } from "./src/plugins/schema-page";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const repoRoot = path.resolve(__dirname, "..");
const schemaModuleNames = new Set(
  getSchemaModules(repoRoot).map((m) => m.name),
);

/** Title-case a kebab/snake module name, e.g. "bible-core" → "Bible Core". */
function toLabel(name: string): string {
  return name
    .split(/[-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

/** Return the sorted list of module directories that exist under docs/modules/. */
function getModuleDirNames(): string[] {
  const modulesDocDir = path.join(__dirname, "docs/modules");
  try {
    return fs
      .readdirSync(modulesDocDir, { withFileTypes: true })
      .filter((e) => e.isDirectory() || e.isSymbolicLink())
      .map((e) => e.name)
      .sort();
  } catch {
    return [];
  }
}

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",
    {
      type: "category",
      label: "System Design",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "system-design" }],
    },
    {
      type: "category",
      label: "Modules",
      link: { type: "doc", id: "modules/index" },
      items: getModuleDirNames().map((modName) => ({
        type: "category" as const,
        label: toLabel(modName),
        link: { type: "doc" as const, id: `modules/${modName}/index` },
        items: [
          { type: "autogenerated" as const, dirName: `modules/${modName}` },
          ...(schemaModuleNames.has(modName) ?
            [
              {
                type: "link" as const,
                label: "Schema",
                href: `/modules/${modName}/schema`,
              },
            ]
          : []),
        ],
      })),
    },
  ],
};

export default sidebars;
