/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as landingIndexRouteImport } from "./routes/(landing)/index";

const landingIndexRoute = landingIndexRouteImport.update({
  id: "/(landing)/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof landingIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof landingIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/(landing)/": typeof landingIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/";
  id: "__root__" | "/(landing)/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  landingIndexRoute: typeof landingIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(landing)/": {
      id: "/(landing)/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof landingIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  landingIndexRoute: landingIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
