/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./root";
import { Route as modulesLandingUiLandingRouteRouteImport } from "./modules/landing/ui/LandingRoute";

const modulesLandingUiLandingRouteRoute =
  modulesLandingUiLandingRouteRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof modulesLandingUiLandingRouteRoute;
}
export interface FileRoutesByTo {
  "/": typeof modulesLandingUiLandingRouteRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof modulesLandingUiLandingRouteRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/";
  id: "__root__" | "/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  modulesLandingUiLandingRouteRoute: typeof modulesLandingUiLandingRouteRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof modulesLandingUiLandingRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  modulesLandingUiLandingRouteRoute: modulesLandingUiLandingRouteRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
