/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as MinimalRouteRouteImport } from "./routes/_minimal/route";
import { Route as MainRouteRouteImport } from "./routes/_main/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as EmailNotificationsRouteImport } from "./routes/email.notifications";
import { Route as MinimalVerifyEmailRouteImport } from "./routes/_minimal/verify-email";
import { Route as MinimalResetPasswordRouteImport } from "./routes/_minimal/reset-password";
import { Route as MinimalLoginRouteImport } from "./routes/_minimal/login";
import { Route as MinimalInviteRouteImport } from "./routes/_minimal/invite";
import { Route as MinimalForgotPasswordRouteImport } from "./routes/_minimal/forgot-password";
import { Route as MainProfileRouteImport } from "./routes/_main/profile";
import { Route as MainFeaturesRouteImport } from "./routes/_main/features";
import { Route as MainDashboardRouteImport } from "./routes/_main/dashboard";
import { Route as mainTranslateDotDotDotDotDotDotUiTranslationRoutesRouteRouteImport } from "./ui/translation/routes/route";
import { Route as mainReadDotDotDotDotDotDotUiStudyRoutesRouteRouteImport } from "./ui/study/routes/route";
import { Route as mainDownloadsDotDotDotDotDotDotUiDownloadsRoutesRouteRouteImport } from "./ui/downloads/routes/route";
import { Route as mainAdminDotDotDotDotDotDotUiAdminRoutesIndexRouteImport } from "./ui/admin/routes/index";
import { Route as mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeRouteImport } from "./ui/translation/routes/$code";
import { Route as mainReadDotDotDotDotDotDotUiStudyRoutesCodeRouteImport } from "./ui/study/routes/$code";
import { Route as MainPSplatRouteImport } from "./routes/_main/p.$";
import { Route as mainAdminDotDotDotDotDotDotUiAdminRoutesJobsRouteImport } from "./ui/admin/routes/jobs";
import { Route as mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeDotverseIdRouteImport } from "./ui/translation/routes/$code.$verseId";
import { Route as mainReadDotDotDotDotDotDotUiStudyRoutesCodeDotchapterIdRouteImport } from "./ui/study/routes/$code.$chapterId";
import { Route as mainAdminDotDotDotDotDotDotUiAdminRoutesUsersInviteRouteImport } from "./ui/admin/routes/users/invite";
import { Route as mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesNewRouteImport } from "./ui/admin/routes/languages/new";
import { Route as mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRouteImport } from "./ui/admin/routes/languages.$code/route";
import { Route as mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeIndexRouteImport } from "./ui/admin/routes/languages.$code/index";
import { Route as mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeSettingsRouteImport } from "./ui/admin/routes/languages.$code/settings";
import { Route as mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeInviteRouteImport } from "./ui/admin/routes/languages.$code/invite";
import { Route as mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeExportsRouteImport } from "./ui/admin/routes/languages.$code/exports";

const MinimalRouteRoute = MinimalRouteRouteImport.update({
  id: "/_minimal",
  getParentRoute: () => rootRouteImport,
} as any);
const MainRouteRoute = MainRouteRouteImport.update({
  id: "/_main",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const EmailNotificationsRoute = EmailNotificationsRouteImport.update({
  id: "/email/notifications",
  path: "/email/notifications",
  getParentRoute: () => rootRouteImport,
} as any);
const MinimalVerifyEmailRoute = MinimalVerifyEmailRouteImport.update({
  id: "/verify-email",
  path: "/verify-email",
  getParentRoute: () => MinimalRouteRoute,
} as any);
const MinimalResetPasswordRoute = MinimalResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => MinimalRouteRoute,
} as any);
const MinimalLoginRoute = MinimalLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => MinimalRouteRoute,
} as any);
const MinimalInviteRoute = MinimalInviteRouteImport.update({
  id: "/invite",
  path: "/invite",
  getParentRoute: () => MinimalRouteRoute,
} as any);
const MinimalForgotPasswordRoute = MinimalForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => MinimalRouteRoute,
} as any);
const MainProfileRoute = MainProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => MainRouteRoute,
} as any);
const MainFeaturesRoute = MainFeaturesRouteImport.update({
  id: "/features",
  path: "/features",
  getParentRoute: () => MainRouteRoute,
} as any);
const MainDashboardRoute = MainDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => MainRouteRoute,
} as any);
const mainTranslateDotDotDotDotDotDotUiTranslationRoutesRouteRoute =
  mainTranslateDotDotDotDotDotDotUiTranslationRoutesRouteRouteImport.update({
    id: "/translate",
    path: "/translate",
    getParentRoute: () => MainRouteRoute,
  } as any);
const mainReadDotDotDotDotDotDotUiStudyRoutesRouteRoute =
  mainReadDotDotDotDotDotDotUiStudyRoutesRouteRouteImport.update({
    id: "/read",
    path: "/read",
    getParentRoute: () => MainRouteRoute,
  } as any);
const mainDownloadsDotDotDotDotDotDotUiDownloadsRoutesRouteRoute =
  mainDownloadsDotDotDotDotDotDotUiDownloadsRoutesRouteRouteImport.update({
    id: "/downloads",
    path: "/downloads",
    getParentRoute: () => MainRouteRoute,
  } as any);
const mainAdminDotDotDotDotDotDotUiAdminRoutesIndexRoute =
  mainAdminDotDotDotDotDotDotUiAdminRoutesIndexRouteImport.update({
    id: "/admin/",
    path: "/admin/",
    getParentRoute: () => MainRouteRoute,
  } as any);
const mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeRoute =
  mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeRouteImport.update({
    id: "/$code",
    path: "/$code",
    getParentRoute: () =>
      mainTranslateDotDotDotDotDotDotUiTranslationRoutesRouteRoute,
  } as any);
const mainReadDotDotDotDotDotDotUiStudyRoutesCodeRoute =
  mainReadDotDotDotDotDotDotUiStudyRoutesCodeRouteImport.update({
    id: "/$code",
    path: "/$code",
    getParentRoute: () => mainReadDotDotDotDotDotDotUiStudyRoutesRouteRoute,
  } as any);
const MainPSplatRoute = MainPSplatRouteImport.update({
  id: "/p/$",
  path: "/p/$",
  getParentRoute: () => MainRouteRoute,
} as any);
const mainAdminDotDotDotDotDotDotUiAdminRoutesJobsRoute =
  mainAdminDotDotDotDotDotDotUiAdminRoutesJobsRouteImport.update({
    id: "/admin/jobs",
    path: "/admin/jobs",
    getParentRoute: () => MainRouteRoute,
  } as any);
const mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeDotverseIdRoute =
  mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeDotverseIdRouteImport.update(
    {
      id: "/$verseId",
      path: "/$verseId",
      getParentRoute: () =>
        mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeRoute,
    } as any,
  );
const mainReadDotDotDotDotDotDotUiStudyRoutesCodeDotchapterIdRoute =
  mainReadDotDotDotDotDotDotUiStudyRoutesCodeDotchapterIdRouteImport.update({
    id: "/$chapterId",
    path: "/$chapterId",
    getParentRoute: () => mainReadDotDotDotDotDotDotUiStudyRoutesCodeRoute,
  } as any);
const mainAdminDotDotDotDotDotDotUiAdminRoutesUsersInviteRoute =
  mainAdminDotDotDotDotDotDotUiAdminRoutesUsersInviteRouteImport.update({
    id: "/admin/users/invite",
    path: "/admin/users/invite",
    getParentRoute: () => MainRouteRoute,
  } as any);
const mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesNewRoute =
  mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesNewRouteImport.update({
    id: "/admin/languages/new",
    path: "/admin/languages/new",
    getParentRoute: () => MainRouteRoute,
  } as any);
const mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRoute =
  mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRouteImport.update(
    {
      id: "/admin/languages/$code",
      path: "/admin/languages/$code",
      getParentRoute: () => MainRouteRoute,
    } as any,
  );
const mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeIndexRoute =
  mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeIndexRouteImport.update(
    {
      id: "/",
      path: "/",
      getParentRoute: () =>
        mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRoute,
    } as any,
  );
const mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeSettingsRoute =
  mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeSettingsRouteImport.update(
    {
      id: "/settings",
      path: "/settings",
      getParentRoute: () =>
        mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRoute,
    } as any,
  );
const mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeInviteRoute =
  mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeInviteRouteImport.update(
    {
      id: "/invite",
      path: "/invite",
      getParentRoute: () =>
        mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRoute,
    } as any,
  );
const mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeExportsRoute =
  mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeExportsRouteImport.update(
    {
      id: "/exports",
      path: "/exports",
      getParentRoute: () =>
        mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRoute,
    } as any,
  );

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/downloads": typeof mainDownloadsDotDotDotDotDotDotUiDownloadsRoutesRouteRoute;
  "/read": typeof mainReadDotDotDotDotDotDotUiStudyRoutesRouteRouteWithChildren;
  "/translate": typeof mainTranslateDotDotDotDotDotDotUiTranslationRoutesRouteRouteWithChildren;
  "/dashboard": typeof MainDashboardRoute;
  "/features": typeof MainFeaturesRoute;
  "/profile": typeof MainProfileRoute;
  "/forgot-password": typeof MinimalForgotPasswordRoute;
  "/invite": typeof MinimalInviteRoute;
  "/login": typeof MinimalLoginRoute;
  "/reset-password": typeof MinimalResetPasswordRoute;
  "/verify-email": typeof MinimalVerifyEmailRoute;
  "/email/notifications": typeof EmailNotificationsRoute;
  "/admin/jobs": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesJobsRoute;
  "/p/$": typeof MainPSplatRoute;
  "/read/$code": typeof mainReadDotDotDotDotDotDotUiStudyRoutesCodeRouteWithChildren;
  "/translate/$code": typeof mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeRouteWithChildren;
  "/admin/": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesIndexRoute;
  "/admin/languages/$code": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRouteWithChildren;
  "/admin/languages/new": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesNewRoute;
  "/admin/users/invite": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesUsersInviteRoute;
  "/read/$code/$chapterId": typeof mainReadDotDotDotDotDotDotUiStudyRoutesCodeDotchapterIdRoute;
  "/translate/$code/$verseId": typeof mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeDotverseIdRoute;
  "/admin/languages/$code/exports": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeExportsRoute;
  "/admin/languages/$code/invite": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeInviteRoute;
  "/admin/languages/$code/settings": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeSettingsRoute;
  "/admin/languages/$code/": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/downloads": typeof mainDownloadsDotDotDotDotDotDotUiDownloadsRoutesRouteRoute;
  "/read": typeof mainReadDotDotDotDotDotDotUiStudyRoutesRouteRouteWithChildren;
  "/translate": typeof mainTranslateDotDotDotDotDotDotUiTranslationRoutesRouteRouteWithChildren;
  "/dashboard": typeof MainDashboardRoute;
  "/features": typeof MainFeaturesRoute;
  "/profile": typeof MainProfileRoute;
  "/forgot-password": typeof MinimalForgotPasswordRoute;
  "/invite": typeof MinimalInviteRoute;
  "/login": typeof MinimalLoginRoute;
  "/reset-password": typeof MinimalResetPasswordRoute;
  "/verify-email": typeof MinimalVerifyEmailRoute;
  "/email/notifications": typeof EmailNotificationsRoute;
  "/admin/jobs": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesJobsRoute;
  "/p/$": typeof MainPSplatRoute;
  "/read/$code": typeof mainReadDotDotDotDotDotDotUiStudyRoutesCodeRouteWithChildren;
  "/translate/$code": typeof mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeRouteWithChildren;
  "/admin": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesIndexRoute;
  "/admin/languages/new": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesNewRoute;
  "/admin/users/invite": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesUsersInviteRoute;
  "/read/$code/$chapterId": typeof mainReadDotDotDotDotDotDotUiStudyRoutesCodeDotchapterIdRoute;
  "/translate/$code/$verseId": typeof mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeDotverseIdRoute;
  "/admin/languages/$code/exports": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeExportsRoute;
  "/admin/languages/$code/invite": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeInviteRoute;
  "/admin/languages/$code/settings": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeSettingsRoute;
  "/admin/languages/$code": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_main": typeof MainRouteRouteWithChildren;
  "/_minimal": typeof MinimalRouteRouteWithChildren;
  "/_main/downloads": typeof mainDownloadsDotDotDotDotDotDotUiDownloadsRoutesRouteRoute;
  "/_main/read": typeof mainReadDotDotDotDotDotDotUiStudyRoutesRouteRouteWithChildren;
  "/_main/translate": typeof mainTranslateDotDotDotDotDotDotUiTranslationRoutesRouteRouteWithChildren;
  "/_main/dashboard": typeof MainDashboardRoute;
  "/_main/features": typeof MainFeaturesRoute;
  "/_main/profile": typeof MainProfileRoute;
  "/_minimal/forgot-password": typeof MinimalForgotPasswordRoute;
  "/_minimal/invite": typeof MinimalInviteRoute;
  "/_minimal/login": typeof MinimalLoginRoute;
  "/_minimal/reset-password": typeof MinimalResetPasswordRoute;
  "/_minimal/verify-email": typeof MinimalVerifyEmailRoute;
  "/email/notifications": typeof EmailNotificationsRoute;
  "/_main/admin/jobs": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesJobsRoute;
  "/_main/p/$": typeof MainPSplatRoute;
  "/_main/read/$code": typeof mainReadDotDotDotDotDotDotUiStudyRoutesCodeRouteWithChildren;
  "/_main/translate/$code": typeof mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeRouteWithChildren;
  "/_main/admin/": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesIndexRoute;
  "/_main/admin/languages/$code": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRouteWithChildren;
  "/_main/admin/languages/new": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesNewRoute;
  "/_main/admin/users/invite": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesUsersInviteRoute;
  "/_main/read/$code/$chapterId": typeof mainReadDotDotDotDotDotDotUiStudyRoutesCodeDotchapterIdRoute;
  "/_main/translate/$code/$verseId": typeof mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeDotverseIdRoute;
  "/_main/admin/languages/$code/exports": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeExportsRoute;
  "/_main/admin/languages/$code/invite": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeInviteRoute;
  "/_main/admin/languages/$code/settings": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeSettingsRoute;
  "/_main/admin/languages/$code/": typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/downloads"
    | "/read"
    | "/translate"
    | "/dashboard"
    | "/features"
    | "/profile"
    | "/forgot-password"
    | "/invite"
    | "/login"
    | "/reset-password"
    | "/verify-email"
    | "/email/notifications"
    | "/admin/jobs"
    | "/p/$"
    | "/read/$code"
    | "/translate/$code"
    | "/admin/"
    | "/admin/languages/$code"
    | "/admin/languages/new"
    | "/admin/users/invite"
    | "/read/$code/$chapterId"
    | "/translate/$code/$verseId"
    | "/admin/languages/$code/exports"
    | "/admin/languages/$code/invite"
    | "/admin/languages/$code/settings"
    | "/admin/languages/$code/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/downloads"
    | "/read"
    | "/translate"
    | "/dashboard"
    | "/features"
    | "/profile"
    | "/forgot-password"
    | "/invite"
    | "/login"
    | "/reset-password"
    | "/verify-email"
    | "/email/notifications"
    | "/admin/jobs"
    | "/p/$"
    | "/read/$code"
    | "/translate/$code"
    | "/admin"
    | "/admin/languages/new"
    | "/admin/users/invite"
    | "/read/$code/$chapterId"
    | "/translate/$code/$verseId"
    | "/admin/languages/$code/exports"
    | "/admin/languages/$code/invite"
    | "/admin/languages/$code/settings"
    | "/admin/languages/$code";
  id:
    | "__root__"
    | "/"
    | "/_main"
    | "/_minimal"
    | "/_main/downloads"
    | "/_main/read"
    | "/_main/translate"
    | "/_main/dashboard"
    | "/_main/features"
    | "/_main/profile"
    | "/_minimal/forgot-password"
    | "/_minimal/invite"
    | "/_minimal/login"
    | "/_minimal/reset-password"
    | "/_minimal/verify-email"
    | "/email/notifications"
    | "/_main/admin/jobs"
    | "/_main/p/$"
    | "/_main/read/$code"
    | "/_main/translate/$code"
    | "/_main/admin/"
    | "/_main/admin/languages/$code"
    | "/_main/admin/languages/new"
    | "/_main/admin/users/invite"
    | "/_main/read/$code/$chapterId"
    | "/_main/translate/$code/$verseId"
    | "/_main/admin/languages/$code/exports"
    | "/_main/admin/languages/$code/invite"
    | "/_main/admin/languages/$code/settings"
    | "/_main/admin/languages/$code/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  MainRouteRoute: typeof MainRouteRouteWithChildren;
  MinimalRouteRoute: typeof MinimalRouteRouteWithChildren;
  EmailNotificationsRoute: typeof EmailNotificationsRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_minimal": {
      id: "/_minimal";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof MinimalRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_main": {
      id: "/_main";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof MainRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/email/notifications": {
      id: "/email/notifications";
      path: "/email/notifications";
      fullPath: "/email/notifications";
      preLoaderRoute: typeof EmailNotificationsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_minimal/verify-email": {
      id: "/_minimal/verify-email";
      path: "/verify-email";
      fullPath: "/verify-email";
      preLoaderRoute: typeof MinimalVerifyEmailRouteImport;
      parentRoute: typeof MinimalRouteRoute;
    };
    "/_minimal/reset-password": {
      id: "/_minimal/reset-password";
      path: "/reset-password";
      fullPath: "/reset-password";
      preLoaderRoute: typeof MinimalResetPasswordRouteImport;
      parentRoute: typeof MinimalRouteRoute;
    };
    "/_minimal/login": {
      id: "/_minimal/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof MinimalLoginRouteImport;
      parentRoute: typeof MinimalRouteRoute;
    };
    "/_minimal/invite": {
      id: "/_minimal/invite";
      path: "/invite";
      fullPath: "/invite";
      preLoaderRoute: typeof MinimalInviteRouteImport;
      parentRoute: typeof MinimalRouteRoute;
    };
    "/_minimal/forgot-password": {
      id: "/_minimal/forgot-password";
      path: "/forgot-password";
      fullPath: "/forgot-password";
      preLoaderRoute: typeof MinimalForgotPasswordRouteImport;
      parentRoute: typeof MinimalRouteRoute;
    };
    "/_main/profile": {
      id: "/_main/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof MainProfileRouteImport;
      parentRoute: typeof MainRouteRoute;
    };
    "/_main/features": {
      id: "/_main/features";
      path: "/features";
      fullPath: "/features";
      preLoaderRoute: typeof MainFeaturesRouteImport;
      parentRoute: typeof MainRouteRoute;
    };
    "/_main/dashboard": {
      id: "/_main/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof MainDashboardRouteImport;
      parentRoute: typeof MainRouteRoute;
    };
    "/_main/translate": {
      id: "/_main/translate";
      path: "/translate";
      fullPath: "/translate";
      preLoaderRoute: typeof mainTranslateDotDotDotDotDotDotUiTranslationRoutesRouteRouteImport;
      parentRoute: typeof MainRouteRoute;
    };
    "/_main/read": {
      id: "/_main/read";
      path: "/read";
      fullPath: "/read";
      preLoaderRoute: typeof mainReadDotDotDotDotDotDotUiStudyRoutesRouteRouteImport;
      parentRoute: typeof MainRouteRoute;
    };
    "/_main/downloads": {
      id: "/_main/downloads";
      path: "/downloads";
      fullPath: "/downloads";
      preLoaderRoute: typeof mainDownloadsDotDotDotDotDotDotUiDownloadsRoutesRouteRouteImport;
      parentRoute: typeof MainRouteRoute;
    };
    "/_main/admin/": {
      id: "/_main/admin/";
      path: "/admin";
      fullPath: "/admin/";
      preLoaderRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesIndexRouteImport;
      parentRoute: typeof MainRouteRoute;
    };
    "/_main/translate/$code": {
      id: "/_main/translate/$code";
      path: "/$code";
      fullPath: "/translate/$code";
      preLoaderRoute: typeof mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeRouteImport;
      parentRoute: typeof mainTranslateDotDotDotDotDotDotUiTranslationRoutesRouteRoute;
    };
    "/_main/read/$code": {
      id: "/_main/read/$code";
      path: "/$code";
      fullPath: "/read/$code";
      preLoaderRoute: typeof mainReadDotDotDotDotDotDotUiStudyRoutesCodeRouteImport;
      parentRoute: typeof mainReadDotDotDotDotDotDotUiStudyRoutesRouteRoute;
    };
    "/_main/p/$": {
      id: "/_main/p/$";
      path: "/p/$";
      fullPath: "/p/$";
      preLoaderRoute: typeof MainPSplatRouteImport;
      parentRoute: typeof MainRouteRoute;
    };
    "/_main/admin/jobs": {
      id: "/_main/admin/jobs";
      path: "/admin/jobs";
      fullPath: "/admin/jobs";
      preLoaderRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesJobsRouteImport;
      parentRoute: typeof MainRouteRoute;
    };
    "/_main/translate/$code/$verseId": {
      id: "/_main/translate/$code/$verseId";
      path: "/$verseId";
      fullPath: "/translate/$code/$verseId";
      preLoaderRoute: typeof mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeDotverseIdRouteImport;
      parentRoute: typeof mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeRoute;
    };
    "/_main/read/$code/$chapterId": {
      id: "/_main/read/$code/$chapterId";
      path: "/$chapterId";
      fullPath: "/read/$code/$chapterId";
      preLoaderRoute: typeof mainReadDotDotDotDotDotDotUiStudyRoutesCodeDotchapterIdRouteImport;
      parentRoute: typeof mainReadDotDotDotDotDotDotUiStudyRoutesCodeRoute;
    };
    "/_main/admin/users/invite": {
      id: "/_main/admin/users/invite";
      path: "/admin/users/invite";
      fullPath: "/admin/users/invite";
      preLoaderRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesUsersInviteRouteImport;
      parentRoute: typeof MainRouteRoute;
    };
    "/_main/admin/languages/new": {
      id: "/_main/admin/languages/new";
      path: "/admin/languages/new";
      fullPath: "/admin/languages/new";
      preLoaderRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesNewRouteImport;
      parentRoute: typeof MainRouteRoute;
    };
    "/_main/admin/languages/$code": {
      id: "/_main/admin/languages/$code";
      path: "/admin/languages/$code";
      fullPath: "/admin/languages/$code";
      preLoaderRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRouteImport;
      parentRoute: typeof MainRouteRoute;
    };
    "/_main/admin/languages/$code/": {
      id: "/_main/admin/languages/$code/";
      path: "/";
      fullPath: "/admin/languages/$code/";
      preLoaderRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeIndexRouteImport;
      parentRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRoute;
    };
    "/_main/admin/languages/$code/settings": {
      id: "/_main/admin/languages/$code/settings";
      path: "/settings";
      fullPath: "/admin/languages/$code/settings";
      preLoaderRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeSettingsRouteImport;
      parentRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRoute;
    };
    "/_main/admin/languages/$code/invite": {
      id: "/_main/admin/languages/$code/invite";
      path: "/invite";
      fullPath: "/admin/languages/$code/invite";
      preLoaderRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeInviteRouteImport;
      parentRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRoute;
    };
    "/_main/admin/languages/$code/exports": {
      id: "/_main/admin/languages/$code/exports";
      path: "/exports";
      fullPath: "/admin/languages/$code/exports";
      preLoaderRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeExportsRouteImport;
      parentRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRoute;
    };
  }
}

interface mainReadDotDotDotDotDotDotUiStudyRoutesCodeRouteChildren {
  mainReadDotDotDotDotDotDotUiStudyRoutesCodeDotchapterIdRoute: typeof mainReadDotDotDotDotDotDotUiStudyRoutesCodeDotchapterIdRoute;
}

const mainReadDotDotDotDotDotDotUiStudyRoutesCodeRouteChildren: mainReadDotDotDotDotDotDotUiStudyRoutesCodeRouteChildren =
  {
    mainReadDotDotDotDotDotDotUiStudyRoutesCodeDotchapterIdRoute:
      mainReadDotDotDotDotDotDotUiStudyRoutesCodeDotchapterIdRoute,
  };

const mainReadDotDotDotDotDotDotUiStudyRoutesCodeRouteWithChildren =
  mainReadDotDotDotDotDotDotUiStudyRoutesCodeRoute._addFileChildren(
    mainReadDotDotDotDotDotDotUiStudyRoutesCodeRouteChildren,
  );

interface mainReadDotDotDotDotDotDotUiStudyRoutesRouteRouteChildren {
  mainReadDotDotDotDotDotDotUiStudyRoutesCodeRoute: typeof mainReadDotDotDotDotDotDotUiStudyRoutesCodeRouteWithChildren;
}

const mainReadDotDotDotDotDotDotUiStudyRoutesRouteRouteChildren: mainReadDotDotDotDotDotDotUiStudyRoutesRouteRouteChildren =
  {
    mainReadDotDotDotDotDotDotUiStudyRoutesCodeRoute:
      mainReadDotDotDotDotDotDotUiStudyRoutesCodeRouteWithChildren,
  };

const mainReadDotDotDotDotDotDotUiStudyRoutesRouteRouteWithChildren =
  mainReadDotDotDotDotDotDotUiStudyRoutesRouteRoute._addFileChildren(
    mainReadDotDotDotDotDotDotUiStudyRoutesRouteRouteChildren,
  );

interface mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeRouteChildren {
  mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeDotverseIdRoute: typeof mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeDotverseIdRoute;
}

const mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeRouteChildren: mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeRouteChildren =
  {
    mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeDotverseIdRoute:
      mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeDotverseIdRoute,
  };

const mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeRouteWithChildren =
  mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeRoute._addFileChildren(
    mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeRouteChildren,
  );

interface mainTranslateDotDotDotDotDotDotUiTranslationRoutesRouteRouteChildren {
  mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeRoute: typeof mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeRouteWithChildren;
}

const mainTranslateDotDotDotDotDotDotUiTranslationRoutesRouteRouteChildren: mainTranslateDotDotDotDotDotDotUiTranslationRoutesRouteRouteChildren =
  {
    mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeRoute:
      mainTranslateDotDotDotDotDotDotUiTranslationRoutesCodeRouteWithChildren,
  };

const mainTranslateDotDotDotDotDotDotUiTranslationRoutesRouteRouteWithChildren =
  mainTranslateDotDotDotDotDotDotUiTranslationRoutesRouteRoute._addFileChildren(
    mainTranslateDotDotDotDotDotDotUiTranslationRoutesRouteRouteChildren,
  );

interface mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRouteChildren {
  mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeExportsRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeExportsRoute;
  mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeInviteRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeInviteRoute;
  mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeSettingsRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeSettingsRoute;
  mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeIndexRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeIndexRoute;
}

const mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRouteChildren: mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRouteChildren =
  {
    mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeExportsRoute:
      mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeExportsRoute,
    mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeInviteRoute:
      mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeInviteRoute,
    mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeSettingsRoute:
      mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeSettingsRoute,
    mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeIndexRoute:
      mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeIndexRoute,
  };

const mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRouteWithChildren =
  mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRoute._addFileChildren(
    mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRouteChildren,
  );

interface MainRouteRouteChildren {
  mainDownloadsDotDotDotDotDotDotUiDownloadsRoutesRouteRoute: typeof mainDownloadsDotDotDotDotDotDotUiDownloadsRoutesRouteRoute;
  mainReadDotDotDotDotDotDotUiStudyRoutesRouteRoute: typeof mainReadDotDotDotDotDotDotUiStudyRoutesRouteRouteWithChildren;
  mainTranslateDotDotDotDotDotDotUiTranslationRoutesRouteRoute: typeof mainTranslateDotDotDotDotDotDotUiTranslationRoutesRouteRouteWithChildren;
  MainDashboardRoute: typeof MainDashboardRoute;
  MainFeaturesRoute: typeof MainFeaturesRoute;
  MainProfileRoute: typeof MainProfileRoute;
  mainAdminDotDotDotDotDotDotUiAdminRoutesJobsRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesJobsRoute;
  MainPSplatRoute: typeof MainPSplatRoute;
  mainAdminDotDotDotDotDotDotUiAdminRoutesIndexRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesIndexRoute;
  mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRouteWithChildren;
  mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesNewRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesNewRoute;
  mainAdminDotDotDotDotDotDotUiAdminRoutesUsersInviteRoute: typeof mainAdminDotDotDotDotDotDotUiAdminRoutesUsersInviteRoute;
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  mainDownloadsDotDotDotDotDotDotUiDownloadsRoutesRouteRoute:
    mainDownloadsDotDotDotDotDotDotUiDownloadsRoutesRouteRoute,
  mainReadDotDotDotDotDotDotUiStudyRoutesRouteRoute:
    mainReadDotDotDotDotDotDotUiStudyRoutesRouteRouteWithChildren,
  mainTranslateDotDotDotDotDotDotUiTranslationRoutesRouteRoute:
    mainTranslateDotDotDotDotDotDotUiTranslationRoutesRouteRouteWithChildren,
  MainDashboardRoute: MainDashboardRoute,
  MainFeaturesRoute: MainFeaturesRoute,
  MainProfileRoute: MainProfileRoute,
  mainAdminDotDotDotDotDotDotUiAdminRoutesJobsRoute:
    mainAdminDotDotDotDotDotDotUiAdminRoutesJobsRoute,
  MainPSplatRoute: MainPSplatRoute,
  mainAdminDotDotDotDotDotDotUiAdminRoutesIndexRoute:
    mainAdminDotDotDotDotDotDotUiAdminRoutesIndexRoute,
  mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRoute:
    mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesDotcodeRouteRouteWithChildren,
  mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesNewRoute:
    mainAdminDotDotDotDotDotDotUiAdminRoutesLanguagesNewRoute,
  mainAdminDotDotDotDotDotDotUiAdminRoutesUsersInviteRoute:
    mainAdminDotDotDotDotDotDotUiAdminRoutesUsersInviteRoute,
};

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
);

interface MinimalRouteRouteChildren {
  MinimalForgotPasswordRoute: typeof MinimalForgotPasswordRoute;
  MinimalInviteRoute: typeof MinimalInviteRoute;
  MinimalLoginRoute: typeof MinimalLoginRoute;
  MinimalResetPasswordRoute: typeof MinimalResetPasswordRoute;
  MinimalVerifyEmailRoute: typeof MinimalVerifyEmailRoute;
}

const MinimalRouteRouteChildren: MinimalRouteRouteChildren = {
  MinimalForgotPasswordRoute: MinimalForgotPasswordRoute,
  MinimalInviteRoute: MinimalInviteRoute,
  MinimalLoginRoute: MinimalLoginRoute,
  MinimalResetPasswordRoute: MinimalResetPasswordRoute,
  MinimalVerifyEmailRoute: MinimalVerifyEmailRoute,
};

const MinimalRouteRouteWithChildren = MinimalRouteRoute._addFileChildren(
  MinimalRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRouteRoute: MainRouteRouteWithChildren,
  MinimalRouteRoute: MinimalRouteRouteWithChildren,
  EmailNotificationsRoute: EmailNotificationsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
